events {
    worker_connections 1024;  # Adjust this value based on your needs
}

http {
    upstream auth_service {
        server auth_service:8001;
    }
    # upstream profile_service {
    #     server profile_service:8002;
    # }
    # upstream rag_service {
    #     server rag_service:8003;
    # }

    server {
        listen 8000;

        location /auth/ {
            proxy_pass http://auth_service/;
        }

        # location /profile/ {
        #     proxy_pass http://profile_service/;
        # }

        # location /rag/ {
        #     proxy_pass http://rag_service/;
        # }
    }
}


curl -X 'POST' \
  'http://192.168.50.193:8000/auth/auth/login' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "string",
  "password": "string"
}'